### ISSUE TITLE
Install fails - requirement python-magic-bin not found

### ISSUE THREAD

**Issue by voidnecron** [xFreed0m/KatzKatz#2]
No matching distribution found for python-magic-bin (from -r requirements.txt (line 3))

Kali 2020.1, default install, apt install python-pip.

**Comment by voidnecron** [comment]
If you don't want to use -F for scraping folders you can comment out requirement line 3 (magic) and use the modded version below:
[https://pastebin.com/6Tg2NAsa](url)

**Comment by xFreed0m** [comment]
python-magic-bin is used when running on Windows, when running on linux the package isn't required.

**Comment by voidnecron** [comment]
Well, I needed to mod the code a bit (see pastebin) to get it working without python-magic-bin.
For instance the import part fails because it cannot find the module, and the check when using -F fails (line 87, 88 and 89)
